services:
  - type: web
    name: finacy-backend
    runtime: node
    plan: free
    buildCommand: cd packages/backend && npm install -g pnpm && pnpm install && pnpm build
    startCommand: cd packages/backend && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
